/**
 * Generates the shipped CSS from the TypeScript token source.
 *
 * Run via `pnpm build:tokens` (and automatically as part of `pnpm build`).
 * Everything it writes is gitignored — the `.ts` files under
 * `src/tokens/source` are the only thing to edit.
 *
 * Output:
 *   src/styles/tokens.css               primitives + default brand ramp
 *   src/styles/themes/light.css         light semantic mapping
 *   src/styles/themes/dark.css          dark semantic mapping
 *   src/styles/themes/brands/<name>.css brand ramps
 */

import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { primitives } from '../src/tokens/source/primitives.js';
import { themes, type SemanticTokens } from '../src/tokens/source/semantic.js';
import { brands, defaultBrand, type Brand } from '../src/tokens/source/brands/index.js';
import { flatten, toCssValue, toCssVarName } from '../src/tokens/resolve.js';

const here = dirname(fileURLToPath(import.meta.url));
const stylesDir = join(here, '..', 'src', 'styles');

const BANNER = `/*
 * DO NOT EDIT — generated by scripts/build-tokens.ts.
 * Edit the token source under src/tokens/source and run \`pnpm build:tokens\`.
 */
`;

const indent = (lines: string[]): string => lines.map((line) => `  ${line}`).join('\n');

function declarations(entries: Iterable<[string, string]>): string[] {
  return [...entries].map(([name, value]) => `${name}: ${value};`);
}

/** Primitive tokens plus the default brand ramp, on `:root`. */
function buildTokensCss(): string {
  const primitiveDecls = declarations(flatten(primitives));
  const rampDecls = declarations(brandRampEntries(defaultBrand));

  return `${BANNER}
:root {
${indent(primitiveDecls)}

  /* Default brand ramp. Override with [data-brand="…"]. */
${indent(rampDecls)}
}
`;
}

function brandRampEntries(brand: Brand): Array<[string, string]> {
  return Object.entries(brand.ramp).map(([stop, value]) => [toCssVarName(['brand', stop]), value]);
}

function semanticDeclarations(tokens: SemanticTokens): string[] {
  const entries = flatten({ color: tokens.color });
  return [
    `color-scheme: ${tokens.colorScheme};`,
    ...declarations([...entries].map(([name, value]) => [name, toCssValue(value)])),
  ];
}

/**
 * Light is emitted on `:root` as well as `[data-theme="light"]` so the library
 * renders correctly with no attribute set at all — no JavaScript, no
 * ThemeProvider, no inline script. That is the floor: the system must work when
 * everything else fails.
 *
 * The `prefers-color-scheme` block gives no-JS users their OS preference, and
 * is scoped with `:not([data-theme])` so an explicit choice always wins.
 */
function buildLightCss(): string {
  const decls = semanticDeclarations(themes.light);
  return `${BANNER}
:root,
[data-theme='light'] {
${indent(decls)}
}
`;
}

function buildDarkCss(): string {
  const decls = semanticDeclarations(themes.dark);
  return `${BANNER}
[data-theme='dark'] {
${indent(decls)}
}

/* No-JS fallback: honour the OS preference unless a theme was set explicitly. */
@media (prefers-color-scheme: dark) {
  :root:not([data-theme]) {
${indent(decls.map((line) => `  ${line}`))}
  }
}
`;
}

/**
 * The default brand is emitted on `:root` too (in tokens.css), so that
 * `[data-brand]` is genuinely optional. Each brand file only ever declares ramp
 * stops — never semantic roles — which is why brands and themes can never fight
 * over specificity.
 */
function buildBrandCss(brand: Brand): string {
  const decls = declarations(brandRampEntries(brand));
  return `${BANNER}
[data-brand='${brand.name}'] {
${indent(decls)}
}
`;
}

async function write(relativePath: string, contents: string): Promise<void> {
  const target = join(stylesDir, relativePath);
  await mkdir(dirname(target), { recursive: true });
  await writeFile(target, contents, 'utf8');
  console.log(`  generated  src/styles/${relativePath.replaceAll('\\', '/')}`);
}

async function main(): Promise<void> {
  console.log('Building design tokens…');

  await write('tokens.css', buildTokensCss());
  await write(join('themes', 'light.css'), buildLightCss());
  await write(join('themes', 'dark.css'), buildDarkCss());

  for (const brand of Object.values(brands)) {
    await write(join('themes', 'brands', `${brand.name}.css`), buildBrandCss(brand));
  }

  console.log('Done.');
}

main().catch((error: unknown) => {
  console.error(error);
  process.exitCode = 1;
});
